## Machine Learning Pipeline

As the class practice, the students will be required to develop a machine learning pipeline using the `Churn_Modelling_train_test.csv` dataset.

**About dataset**

This dataset is obained from [kaggle](https://www.kaggle.com/datasets/shubhammeshram579/bank-customer-churn-prediction?resource=download). It contains information on bank customers who either left the bank or continue to be a customer. The dataset includes the following attributes:

* Customer ID: A unique identifier for each customer
* Surname: The customer's surname or last name
* Credit Score: A numerical value representing the customer's credit score
* Geography: The country where the customer resides (France, Spain or Germany)
* Gender: The customer's gender (Male or Female)
* Age: The customer's age.
* Tenure: The number of years the customer has been with the bank
* Balance: The customer's account balance
* NumOfProducts: The number of bank products the customer uses (e.g., savings account, credit card)
* HasCrCard: Whether the customer has a credit card (1 = yes, 0 = no)
* IsActiveMember: Whether the customer is an active member (1 = yes, 0 = no)
* EstimatedSalary: The estimated salary of the customer
* Exited: Whether the customer has churned (1 = yes, 0 = no)

### Exploratory Data Analysis

In this section the students are required to do an EDA to understand the dataset.

In [1]:
# import packages
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score

In [ ]:
# Load the dataset" \
df = pd.read_csv("Churn_Modelling_train_test.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,Female,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,Male,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,Male,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,Male,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,Female,69.0,5,86038.21,3,0.0,0.0,192743.06,1

In [3]:
# dataset analysis

print("shape:")
print(df.shape)

print("\ninfo:")
print(df.info())

print("\nmissing values:")
print(df.isnull().sum())

print("\nduplicates:")
print(df.duplicated().sum())

print("\nsummary statistics:")
display(df.describe())

shape:
(9001, 14)

info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9001 entries, 0 to 9000
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9001 non-null   int64
 1   CustomerId       9001 non-null   int64
 2   Surname          9001 non-null   object
 3   CreditScore      9001 non-null   int64
 4   Geography        9000 non-null   object
 5   Gender           9001 non-null   object
 6   Age              9000 non-null   float64
 7   Tenure           9001 non-null   int64
 8   Balance          9001 non-null   float64
 9   NumOfProducts    9001 non-null   int64
 10  HasCrCard        9000 non-null   float64
 11  IsActiveMember   9001 non-null   float64
 12  EstimatedSalary  9001 non-null   float64
 13  Exited           9001 non-null   int64
dtypes: float64(5), int64(6), object(3)
memory usage: 984.6+ KB
None

missing values:
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

duplicates:
2

summary statistics:

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,9001.000000,9.001000e+03,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000
mean,5003.366515,1.569072e+07,650.681369,38.901781,5.007888,76222.210827,1.531497,0.705667,0.514721,100180.823967,0.204422
std,2884.787499,7.179353e+04,96.539591,10.450760,2.894025,62432.198151,0.579398,0.455768,0.499811,57561.189534,0.403301
min,2.000000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,2509.000000,1.562811e+07,584.000000,32.000000,2.000000,0.000000,1.000000,0.000000,0.000000,50972.600000,0.000000
50%,4989.000000,1.569096e+07,652.000000,37.000000,5.000000,96997.090000,1.000000,1.000000,1.000000,100556.980000,0.000000
75%,7505.000000,1.575265e+07,718.000000,44.000000,7.000000,127450.140000,2.000000,1.000000,1.000000,149458.730000,0.000000
max,10000.000000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [ ]:
# review categorical variables

categorical_columns = [
    "Geography",
    "Gender"
]
for col in categorical_columns:
    print(col)
    print(df[col].value_counts())
    print()

Geography
Geography
France     4505
Spain      2250
Germany    2245
Name: count, dtype: int64

Gender
Gender
Male      4906
Female    4095
Name: count, dtype: int64

In [5]:
# review binary variables
    
binary_columns = [
    "HasCrCard",
    "IsActiveMember",
    "Exited"
]

for col in binary_columns:
    print(col)
    print(df[col].value_counts())
    print()

HasCrCard
HasCrCard
1.0    6351
0.0    2649
Name: count, dtype: int64

IsActiveMember
IsActiveMember
1.0    4633
0.0    4368
Name: count, dtype: int64

Exited
Exited
0    7161
1    1840
Name: count, dtype: int64

In [6]:
# review numerical variables

numerical_columns = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "EstimatedSalary"
]

df[numerical_columns].describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
count,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000,9001.000000
mean,650.681369,38.901781,5.007888,76222.210827,1.531497,100180.823967
std,96.539591,10.450760,2.894025,62432.198151,0.579398,57561.189534
min,350.000000,18.000000,0.000000,0.000000,1.000000,11.580000
25%,584.000000,32.000000,2.000000,0.000000,1.000000,50972.600000
50%,652.000000,37.000000,5.000000,96997.090000,1.000000,100556.980000
75%,718.000000,44.000000,7.000000,127450.140000,2.000000,149458.730000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,199992.480000

**EDA Conclusions**

From this Exploratory Data Analysis we can retrieve the following information:

* The dataset contains customer information and the target column is `Exited`.
* `Exited = 1` means the customer left the bank and `Exited = 0` means the customer stayed.
* The dataset has numerical columns such as `CreditScore`, `Age`, `Balance` and `EstimatedSalary`.
* The categorical columns are `Geography` and `Gender`, so they need to be converted into numbers before training the model.
* Columns such as `RowNumber`, `CustomerId` and `Surname` are identifiers and are not useful for prediction.
* The target variable is imbalanced, because there are more customers who stayed than customers who left.

### ML Pipeline

In this section the students are required to create a ML pipeline to predict whether the customer left the bank or not.

In [1]:
# import packages
import pandas as pd
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, f1_score, classification_report

In [2]:
# Load the dataset
df = pd.read_csv("Churn_Modelling_train_test.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,Female,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,Male,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,Male,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,Male,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,Female,69.0,5,86038.21,3,0.0,0.0,192743.06,1

SyntaxError: 'return' outside function (3597318559.py, line 87)

In [13]:
# balance the dataset (if you think it is necessary)

df["Exited"].value_counts(normalize = True)

Exited
0    0.795578
1    0.204422
Name: proportion, dtype: float64

In [ ]:
# Train a decision tree model using the `train sample`
...

In [ ]:
# Check the accuracy of the model on the `test sample`
...

### MLFlow Integration

In this section the students are required to track the model and the parameters into MLFlow.

In [2]:
# import packages for mlfow
import mlflow

/Users/austevalentukeviciute/Desktop/MLOPS/mlops-and-system-design/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/austevalentukeviciute/Desktop/MLOPS/mlops-and-system-design/.venv/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/austevalentukeviciute/Desktop/MLOPS/mlops-and-system-design/.venv/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

Start a local Tracking server on port 8080 - it is necessary to import mlflow and open a new terminal

In [ ]:
# Set our tracking server uri for logging on port 8080
mlflow.set_tracking_uri(uri="http://127.0.0.1:8080")

Visit the MLFlow UI on `http://127.0.0.1:8080`

In [ ]:
# Create a new MLflow Experiment called `Practice Experiment - {Your Name}`
...

In [ ]:
# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters

    # Log the loss metric

    # Set a tag that we can use to remind ourselves what this run was for
    # Info about tags is pending

    # Infer the model signature

    # Log the model

### Keep practicing

In [3]:
# Create a new experiment using other models or different parameters
...